node_uuid: 1448f0a6-1e0b-11ed-b972-0242ac110002
redpanda:
    data_directory: /var/lib/redpanda/data
    node_id: 0
    seed_servers: []
    rpc_server:
        address: 0.0.0.0
        port: 33145
    kafka_api:
        - address: 0.0.0.0
          port: 29092
          name: PLAINTEXT
        - address: 0.0.0.0
          port: 9092
          name: OUTSIDE
    admin:
        - address: 0.0.0.0
          port: 9644
    advertised_kafka_api:
        - address: redpanda
          port: 29092
          name: PLAINTEXT
        - address: localhost
          port: 9092
          name: OUTSIDE
    developer_mode: true
    auto_create_topics_enabled: true
    enable_coproc: true
    group_topic_partitions: 3
    storage_min_free_bytes: 10485760
    topic_partitions_per_shard: 1000
rpk:
    enable_usage_stats: true
    coredump_dir: /var/lib/redpanda/coredump
    overprovisioned: true
pandaproxy:
    pandaproxy_api:
        - address: 0.0.0.0
          port: 28082
          name: PLAINTEXT
        - address: 0.0.0.0
          port: 8082
          name: OUTSIDE
    advertised_pandaproxy_api:
        - address: redpanda
          port: 28082
          name: PLAINTEXT
        - address: localhost
          port: 8082
          name: OUTSIDE
schema_registry: {}
